# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMainApp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwidget = MPL_WIDGET(self.centralwidget)
        self.mplwidget.setObjectName("mplwidget")
        self.horizontalLayout.addWidget(self.mplwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_lamda = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_lamda.setObjectName("label_lamda")
        self.verticalLayout.addWidget(self.label_lamda)
        self.SpinBox_lambda = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_lambda.setDecimals(1)
        self.SpinBox_lambda.setMinimum(100.0)
        self.SpinBox_lambda.setMaximum(1000.0)
        self.SpinBox_lambda.setSingleStep(100.0)
        self.SpinBox_lambda.setObjectName("SpinBox_lambda")
        self.verticalLayout.addWidget(self.SpinBox_lambda)
        self.slider_lambda = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_lambda.setMinimum(100)
        self.slider_lambda.setMaximum(1000)
        self.slider_lambda.setSingleStep(200)
        self.slider_lambda.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lambda.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_lambda.setObjectName("slider_lambda")
        self.verticalLayout.addWidget(self.slider_lambda)
        self.label_d = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_d.setObjectName("label_d")
        self.verticalLayout.addWidget(self.label_d)
        self.SpinBox_d = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_d.setDecimals(1)
        self.SpinBox_d.setMinimum(1)
        self.SpinBox_d.setMaximum(100)
        self.SpinBox_d.setSingleStep(1)
        self.SpinBox_d.setObjectName("SpinBox_d")
        self.verticalLayout.addWidget(self.SpinBox_d)
        self.Slider_d = QtWidgets.QSlider(self.dockWidgetContents)
        self.Slider_d.setMaximum(100)
        self.Slider_d.setSingleStep(10)
        self.Slider_d.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_d.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_d.setObjectName("Slider_d")
        self.verticalLayout.addWidget(self.Slider_d)
        self.label_I0 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_I0.setObjectName("label_I0")
        self.verticalLayout.addWidget(self.label_I0)
        self.SpinBox_I0 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_I0.setDecimals(1)
        self.SpinBox_I0.setMinimum(0.1)
        self.SpinBox_I0.setObjectName("SpinBox_I0")
        self.verticalLayout.addWidget(self.SpinBox_I0)
        self.slider_I0 = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_I0.setMinimum(1)
        self.slider_I0.setMaximum(100)
        self.slider_I0.setOrientation(QtCore.Qt.Horizontal)
        self.slider_I0.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_I0.setObjectName("slider_I0")
        self.verticalLayout.addWidget(self.slider_I0)
        self.label_l = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_l.setObjectName("label_l")
        self.verticalLayout.addWidget(self.label_l)
        self.SpinBox_l = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_l.setDecimals(1)
        self.SpinBox_l.setMinimum(1.0)
        self.SpinBox_l.setMaximum(10.0)
        self.SpinBox_l.setSingleStep(0.1)
        self.SpinBox_l.setObjectName("SpinBox_l")
        self.verticalLayout.addWidget(self.SpinBox_l)
        self.slider_l = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_l.setMinimum(1)
        self.slider_l.setMaximum(10)
        self.slider_l.setSingleStep(0.1)
        self.slider_l.setOrientation(QtCore.Qt.Horizontal)
        self.slider_l.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_l.setObjectName("slider_l")
        self.verticalLayout.addWidget(self.slider_l)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Sitting"))
        self.label_lamda.setText(_translate("MainWindow", "Wave length(10e-9m)"))
        self.label_d.setText(_translate("MainWindow", "d(1e-6)"))
        self.label_I0.setText(_translate("MainWindow", "I0(1e-6)"))
        self.label_l.setText(_translate("MainWindow", "L(m)"))

from mplwidget import MPL_WIDGET

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

